[package]
name = "cmsis-dap-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
base64 = "0.22"
gdbstub = "=0.7.8"
itertools = "0.15"
object = { version = "0.39", default-features = false, features = ["read", "std"] }
parking_lot = "0.12"
probe-rs.workspace = true
serde.workspace = true
serde_json.workspace = true
svd-parser.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "sync"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
